support gpg2, fix issue overwriting file when password incorrect

diff --git a/pw b/pw
--- a/pw
+++ b/pw
@@ -1,199 +1,265 @@
-#!/bin/bash
+#!/usr/bin/env node
+'use strict';
 
-# pw
-#
-# Commandline bash script for storing and retreiving passwords
-# encrypted using PGP. Store website, username/email and password.
-# Places password into clipboard for easy pasting into website or app.
-#
-# Works on Linux, Windows and Mac.
-#
-# Find pw and other useful scripts at https://github.com/PhilT/bin
-#
-# version 0.7 - Fixed incorrect use of extended bash if
-#               Added description
-# version 0.6 - Silence some verbose commands
-# version 0.5 - Add support for OSX
-#               Overwrite existing passwords (--force)
-#               15 character passwords including symbols
-#               Optional safe characters (--safe)
-# version 0.4 - Add support for Git Bash aka MinGW
-# version 0.3 - generate password and copy to clipboard
-#               Don't re-encrypt file if not changed
-#               Copy retrieved password to clipboard
-#               Improve display of multiple passwords
-# version 0.2 - Added --edit command
-# version 0.1 - Not much error handling yet.
-#
-# Add to ~/bin/pw and chmod +x it.
-# See bottom of file for usage or run `pw` without args.
+// pw
+//
+// Script for storing and retreiving account credentials encrypted using PGP.
+// Store website, username/email and password.
+// Places password into clipboard for easy pasting into website or app.
+//
+// Tested on Linux, Windows and Mac.
+//
+// Only dependency is node (No node modules are required).
+//
+// Find pw and other useful scripts at https://github.com/PhilT/bin
+//
+// version 0.9 - Fix compatibility issues with GPG2
+//               fix an issue with overwritten password file
+// version 0.8 - Convert to Node.js
+//               Implemented new password generation algorithm
+//               Removed safe option. Use only alphanumeric but 20 chars.
+//               implemented query (all) (instead of edit)
+//               commands explicitly specified now
+// version 0.7 - Fixed incorrect use of extended bash if
+//               Added description
+// version 0.6 - Silence some verbose commands
+// version 0.5 - Add support for OSX
+//               Overwrite existing passwords (--force)
+//               15 character passwords including symbols
+//               Optional safe characters (--safe)
+// version 0.4 - Add support for Git Bash aka MinGW
+// version 0.3 - generate password and copy to clipboard
+//               Don't re-encrypt file if not changed
+//               Copy retrieved password to clipboard
+//               Improve display of multiple passwords
+// version 0.2 - Added --edit command
+// version 0.1 - Not much error handling yet.
+//
+// Add to ~/bin/pw and chmod +x it.
+// See bottom of file for usage or run `pw` without args.
+//
 
-if [[ -f ~/.pwconfig ]]; then
-  source ~/.pwconfig
-fi
+var path = require('path'),
+    spawn = require('child_process').spawn,
+    fs = require('fs'),
+    view = require('./lib/pw/view'),
+    flow = require('./lib/pw/flow'),
+    attemptExit = require('./lib/pw/flow').attemptExit,
+    wantToExit = require('./lib/pw/flow').wantToExit,
+    homePath = (process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE),
+    commands = require('./lib/pw/commands'),
+    params = {args: [], force: false},
+    enterPassword,
+    extractOptions,
+    gpg,
+    loadConfig,
+    loadFile,
+    loadJson,
+    loadPasswordFile,
+    parseArgs,
+    processCommand,
+    savePasswordFile,
+    start,
+    usage;
 
-if [[ -z $PASSWORD_DIR || -z $PASSWORD_FILE || -z $EDIT ]]; then
-  echo 'A ~/.pwconfig file must exist with the following configuration:'
-  echo 'PASSWORD_DIR=password/dir (no trailing slash)'
-  echo 'PASSWORD_FILE=.password.csv (no gpg extension)'
-  echo 'EDIT=path/to/editor'
-  echo ''
-  exit 1
-fi
+process.on('SIGINT', function () {
+  process.exit();
+});
 
-PASSWORD_GPG=$PASSWORD_DIR/$PASSWORD_FILE.gpg
-PASSWORD_TEMP=/tmp/$PASSWORD_FILE
+enterPassword = function enterPassword(callback) {
+  var password = '',
+      stdin = process.stdin;
 
-if [[ ! -d $PASSWORD_DIR ]]; then
-  echo $PASSWORD_DIR does not exist. Check ~/.pwconfig
-  exit 1
-fi
+  stdin.setEncoding('utf8');
+  stdin.setRawMode(true);
+  stdin.on('readable', function () {
+    var ch = stdin.read();
+    if (ch === "\r") {
+      stdin.setRawMode(false);
+      stdin.setEncoding();
+      callback(password);
+    } else if (ch === "\u0003") {
+      view.write();
+      process.exit();
+    } else if (ch !== null) {
+      password += ch;
+    }
+  });
+};
 
-if [[ ! -f $PASSWORD_GPG ]]; then
-  echo $PASSWORD_GPG does not exist. Check ~/.pwconfig
-  exit 1
-fi
+extractOptions = function extractOptions() {
+  var index = params.args.indexOf('--force');
+  if (index > -1) {
+    params.args.splice(index, 1);
+    params.force = true;
+  }
+};
 
-if [[ $# > 0 ]]; then
-  echo 'Enter encryption password:'
-  read -s secret
-  OPTIONS=--no-permission-warning\ --no-secmem-warning\ --force-mdc\ --no-tty\ -q\ --no-use-agent\ --yes\ --passphrase=$secret\ --homedir\ ~/.gnupg
-fi
+gpg = function gpg(password, encrypt, input, done, to) {
+  var options = {},
+      args = [
+        '--no-permission-warning',
+        '--no-secmem-warning',
+        '--force-mdc',
+        '--no-tty',
+        '--quiet',
+        '--yes',
+        '--batch',
+        '--passphrase',
+        password,
+        '--homedir',
+        path.join(homePath, '.gnupg')
+      ],
+      child,
+      passwords = '';
 
-function encrypt {
-  gpg $OPTIONS -c -o $PASSWORD_GPG $PASSWORD_TEMP > /dev/null 2>&1
-  cleanup
-  echo 'Password file updated.'
-}
+  if (encrypt) {
+    args.push('--symmetric');
+  } else {
+    args.push('--decrypt');
+  }
+  child = spawn('gpg', args, options);
+  child.on('exit', function () {
+    done(passwords);
+  });
+  if (to) {
+    child.stdout.pipe(to);
+  } else {
+    child.stdout.on('data', function (data) {
+      passwords += data;
+    });
+  }
+  child.stderr.on('data', function (data) {
+    view.write(data.toString());
+    process.exit(1);
+  });
 
-function decrypt {
-  gpg $OPTIONS -o $PASSWORD_TEMP $PASSWORD_GPG > /dev/null 2>&1
-}
+  child.stdin.end(input);
+};
 
-function backup_decrypted_file {
-  cp $PASSWORD_TEMP $PASSWORD_TEMP.bak > /dev/null 2>&1
-}
+loadConfig = function loadConfig(pathname) {
+  var config = loadJson(pathname);
+  config.passwordLength = config.passwordLength || 15;
 
-function cleanup {
-  rm -f $PASSWORD_TEMP $PASSWORD_TEMP.bak > /dev/null 2>&1
-}
+  if (!config.dir || !config.file) {
+    view.write(pathname + ' must exist with, for example:');
+    view.write('{"dir": "path/to/password/file", "file": ".password.csv"}');
+    process.exit(1);
+  }
+  return config;
+};
 
-function init_password_csv {
-  encrypt
-}
+loadFile = function loadFile(pathname, encoding) {
+  var contents;
+  try {
+    contents = fs.readFileSync(pathname, encoding);
+  } catch (e) {
+    view.write('Could not load file: ' + pathname);
+    process.exit(1);
+  }
+  return contents;
+};
 
-function edit_password_csv {
-  decrypt
-  backup_decrypted_file
-  $EDIT $PASSWORD_TEMP
-  if diff $PASSWORD_TEMP $PASSWORD_TEMP.bak > /dev/null 2>&1; then
-    cleanup
-    echo 'No changes made.'
-  else
-    encrypt
-  fi
-}
+loadJson = function loadJson(pathname) {
+  return JSON.parse(loadFile(pathname, 'utf8')) || {};
+};
 
-function add_password {
-  decrypt
-  site_matched=`cat $PASSWORD_TEMP | grep -q "$1,.*,.*"`
-  if [[ $site_matched == 0 || $FORCE ]]; then
-    pass=`LC_ALL=C tr -dc $PASSWORD_CHARS < /dev/urandom | head -c15`
+loadPasswordFile = function loadPasswordFile(pathname, password, callback) {
+  var encryptedPasswords = loadFile(pathname);
+  if (!encryptedPasswords) { throw new Error('Could not load file'); }
+  gpg(password, false, encryptedPasswords, function (passwords) {
+    callback(passwords);
+  });
+};
 
-    copy_password
-    echo Password copied to clipboard.
+parseArgs = function parseArgs() {
+  var command,
+      commands = ['add', 'remove', 'generate', 'query'],
+      index;
 
-    if [[ $site_matched == 0 ]]; then
-      echo $1,$2,$pass >> $PASSWORD_TEMP
-    else
-      if [[ `uname` == 'Darwin' ]]; then
-        INLINE="-i ''"
-      else
-        INLINE="-i"
-      fi
-      sed $INLINE "s/$1,.*,.*/$1,$2,$pass/" $PASSWORD_TEMP
-    fi
-    encrypt
-  else
-    cleanup
-    echo Password for $1 already exists. Use --force to overwrite
-  fi
-}
+  params.args = process.argv.slice(2);
+  extractOptions(params);
+  command = params.args.shift();
 
-function copy_password {
-  if [[ $TERM == 'cygwin' ]]; then
-    echo -n $pass > /dev/clipboard
-  elif which pbcopy > /dev/null 2>&1; then
-    echo -n $pass | pbcopy
-  else
-    echo -n $pass | xsel -i
-  fi
-}
+  commands = commands.concat(commands.map(function (command) { return command[0]; }));
+  index = commands.indexOf(command);
 
-function match_command {
-  cat $PASSWORD_TEMP | sed -n "s/.*$1.*,\(.*\)/\1/p"
-}
+  if (index === -1) {
+    usage();
+    process.exit();
+  }
 
-function matched_site {
-  cat $PASSWORD_TEMP | sed -n "s/\(.*$1.*\),.*,.*/\1/p"
-}
+  return commands[index % (commands.length / 2)];
+};
 
-function matched_login {
-  cat $PASSWORD_TEMP | sed -n "s/.*$1.*,\(.*\),.*/\1/p"
-}
+processCommand = function processCommand(command, password, passwordToAdd) {
+  var pwconfigPath = path.join(homePath, '.pwconfig.json'),
+      pwconfig = loadConfig(pwconfigPath),
+      passwordFile = path.join(pwconfig.dir, pwconfig.file) + '.gpg';
 
-function find_password {
-  decrypt
-  matches=`match_command $1 | wc -l`
-  if [ $matches -eq 0 ]; then
-    echo No matches.
-  elif [ $matches -eq 1 ]; then
-    pass=`match_command $1 | tr -d '\n'`
-    copy_password
-    echo Password for $(matched_site $1) copied to clipboard. Login: $(matched_login $1)
-  else
-    echo Multiple passwords matched. Displaying:
-    cat $PASSWORD_TEMP | grep $1
-  fi
-  rm -f $PASSWORD_TEMP
-}
+  loadPasswordFile(passwordFile, password, function (passwords) {
+    var newPasswords = commands[command](passwords, params, pwconfig, passwordToAdd);
+    flow.wantToExit();
+    if (newPasswords !== passwords && newPasswords && newPasswords !== '') {
+      savePasswordFile(passwordFile, password, newPasswords);
+    }
+    flow.attemptExit();
+  });
+};
 
-if [[ $1 == '--safe' ]]; then
-  shift
-  PASSWORD_CHARS='A-Za-z0-9'
-  echo Using safe password characters
-else
-  PASSWORD_CHARS='A-Za-z0-9_!@#$%^&*()\-+='
-fi
+savePasswordFile = function savePasswordFile(filepath, password, passwords) {
+  wantToExit();
+  gpg(password, true, passwords, function () {
+    view.write('Password file updated.');
+    attemptExit();
+  }, fs.createWriteStream(filepath));
+};
 
-if [[ $1 == '--force' ]]; then
-  FORCE=true
-  shift
-fi
+start = function start() {
+  var command = parseArgs();
 
-if [ $# == 2 ]; then
-  add_password $1 $2
-elif [ $# == 1 ]; then
-  if [ $1 == '--init' ]; then
-    init_password_csv
-  elif [ $1 == '--edit' ]; then
-    edit_password_csv
-  else
-    find_password $1
-  fi
-else
-  echo 'Usage (1): pw --init          Encrypts a prepared .passwords.csv file'
-  echo 'Usage (2): pw --edit          Edit the .passwords.csv file'
-  echo 'Usage (3): pw TERM            find a password containing TERM'
-  echo 'Usage (4): pw [--safe] [--force] URL/NAME LOGIN  add a password (generated and copied to clipboard)'
-  echo 'Add or view a password from a GPG encrypted password file.'
-  echo 'Parameters are in strict order (until getopts is used)'
-  echo
-  echo '--safe        Use upper and lower alphanumeric characters only (no symbols)'
-  echo '--force       Overwrite existing password with new one'
-  echo 'TERM          Enter a partial site name or URL'
-  echo 'URL/NAME      A name or URL of a site'
-  echo 'LOGIN         Email address or username used to login'
-  echo
-  exit
-fi
+  enterPassword(function (password) {
+    if (command === 'add') {
+      enterPassword(function (passwordToAdd) {
+        enterPassword(function (passwordConfirmation) {
+          if (passwordToAdd === passwordConfirmation) {
+            processCommand(command, password, passwordToAdd);
+          } else {
+            view.write("Passwords don't match.");
+          }
+        });
+        view.write('Again to confirm:');
+      });
+      view.write('Enter password to add:');
+    } else {
+      processCommand(command, password);
+    }
+  });
+  view.write('Enter encryption password:');
+};
+
+usage = function usage() {
+  view.write([
+    'pw - generate, store and retrieve encrypted passwords',
+    'install: npm install promise',
+    'usage: pw command options',
+    '',
+    ' command:',
+    '   g, generate url login   creates a new password',
+    '   a, add url login        adds a password generated elsewhere',
+    '   q, query [term]         finds a password or lists matches (or all)',
+    '   r, remove url [login]   removes a password login required when url not unique',
+    '',
+    ' options:',
+    '   --force   overwrite existing password or remove multiple entries',
+    '',
+    ' notes:',
+    '   query will copy a password to clipboard if a single match is found.',
+    '     otherwise it displays all matches',
+    '   delete will only remove a password where the site matches exactly',
+    ''
+  ].join("\n"));
+};
+
+start();
+
